[profile.default]
  auto_detect_solc = false
  bytecode_hash = "none"
  evm_version = "shanghai"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 200
  out = "out"
  script = "script"
  solc = "0.8.20"
  src = "src"
  test = "test"
  libs = ["node_modules"]
  fs_permissions = [
    { access = "write", path = "./log/deployments.json"}
]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
